import type { TaskDetail, TaskSummary } from '@/features/runner/schema'

export const mockTasks: TaskSummary[] = [
  {
    id: 'task-1',
    title: 'QA skate-classics-era-launch against the Vans style guide',
    goal: 'Compare the skate-classics-era-launch campaign HTML in figma-html against the Vans style guide and list every component violation.',
    domain: 'work',
    agentId: null,
    harness: 'codex',
    status: 'running',
    originKind: 'manual',
    ontologyCategoryId: 'newsletter-qa',
    currentStep: 1,
    stepCount: 3,
    costTokens: 4200,
    costUsd: 0.09,
    pendingApprovalId: null,
    riskLevel: 'low',
    createdAt: new Date(Date.now() - 3 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 5_000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Implement SSE in the newsletter-ai BFF',
    goal: 'Push branch feature/sse-bff with the SSE streaming implementation for the newsletter-ai BFF.',
    domain: 'work',
    agentId: null,
    harness: 'codex',
    status: 'waiting_for_approval',
    originKind: 'manual',
    ontologyCategoryId: null,
    currentStep: 0,
    stepCount: 3,
    costTokens: 0,
    costUsd: null,
    pendingApprovalId: 'approval-2',
    riskLevel: 'high',
    createdAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60_000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Summarize the Databricks sync meeting',
    goal: 'Summarize the Databricks sync transcript into decisions, action items, and a follow-up email draft.',
    domain: 'work',
    agentId: null,
    harness: 'codex',
    status: 'completed',
    originKind: 'manual',
    ontologyCategoryId: null,
    currentStep: 3,
    stepCount: 3,
    costTokens: 8_100,
    costUsd: 0.18,
    pendingApprovalId: null,
    riskLevel: 'low',
    createdAt: new Date(Date.now() - 40 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 36 * 60_000).toISOString(),
  },
]

export const mockTaskDetails: Record<string, TaskDetail> = {
  'task-1': {
    ...mockTasks[0],
    planVersion: 1,
    steps: [
      { index: 0, title: 'Classify and check policy', status: 'done' },
      { index: 1, title: 'Run agent', status: 'active' },
      { index: 2, title: 'Record outcome', status: 'pending' },
    ],
    artifacts: [],
    lastEventSeq: 4,
  },
  'task-2': {
    ...mockTasks[1],
    planVersion: 1,
    steps: [
      { index: 0, title: 'Classify and check policy', status: 'done' },
      { index: 1, title: 'Run agent', status: 'pending' },
      { index: 2, title: 'Record outcome', status: 'pending' },
    ],
    artifacts: [],
    lastEventSeq: 1,
  },
  'task-3': {
    ...mockTasks[2],
    planVersion: 1,
    steps: [
      { index: 0, title: 'Classify and check policy', status: 'done' },
      { index: 1, title: 'Run agent', status: 'done' },
      { index: 2, title: 'Record outcome', status: 'done' },
    ],
    artifacts: [
      { id: 'artifact-1', label: 'meeting-summary.md', path: '/vault/work/meeting-summary.md', kind: 'report' },
      { id: 'artifact-2', label: 'follow-up-draft.txt', path: '/vault/work/follow-up-draft.txt', kind: 'draft' },
    ],
    lastEventSeq: 12,
  },
}
