import type { DashboardSnapshot } from '@/features/dashboard/schema'

export const mockDashboardSnapshot: DashboardSnapshot = {
  activity: {
    recentJobs: [
      {
        id: 'job-1',
        inputPath: '~/datasets/catalog.csv',
        maxRuntimeSeconds: 600,
        name: 'Catalog reconciliation',
        outputPath: '~/exports/catalog-registry.json',
        status: 'completed',
        updatedAt: 1_779_844_200_000,
      },
      {
        id: 'job-2',
        inputPath: '~/prompts/catalog-refresh.md',
        maxRuntimeSeconds: 300,
        name: 'Prompt classification pass',
        outputPath: '~/exports/prompt-tags.json',
        status: 'running',
        updatedAt: 1_779_845_400_000,
      },
    ],
    recentThreads: [
      {
        cwd: '~/Documents/projects/agentic-os',
        id: 'thread-1',
        model: 'gpt-5',
        provider: 'openai',
        title: 'Refresh registry architecture',
        tokensUsed: 12_840,
        updatedAt: 1_779_845_100_000,
      },
      {
        cwd: '~/Documents/projects/ops',
        id: 'thread-2',
        model: 'gpt-5-mini',
        provider: 'openai',
        title: 'Review local MCP inventory',
        tokensUsed: 4_120,
        updatedAt: 1_779_841_900_000,
      },
    ],
  },
  catalog: {
    counts: {
      agent: 3,
      automation: 4,
      mcp: 2,
      plugin: 8,
      prompt: 5,
      routine: 4,
      skill: 14,
      workflow: 6,
    },
    items: [
      {
        category: 'skill-pack',
        confidence: 0.98,
        detector: 'codex',
        displayName: 'Playwright',
        entrypoint: '~/.codex/skills/playwright/SKILL.md',
        group: 'Codex',
        id: '~/.codex/skills/playwright/SKILL.md::playwright',
        kind: 'skill',
        name: 'playwright',
        origin: 'Codex skills',
        path: '~/.codex/skills/playwright/SKILL.md',
        provider: 'playwright',
        summary: 'Browser automation workflows for real UI validation.',
        tags: ['browser', 'automation'],
        updatedAt: 1_779_834_000_000,
        version: null,
      },
      {
        category: 'package-manifest',
        confidence: 0.82,
        detector: 'custom-rules',
        displayName: 'newsletter-ai',
        entrypoint: 'dev: vite',
        group: 'newsletter-ai',
        id: '~/Documents/projects/newsletter-ai/package.json::newsletter-ai',
        kind: 'agent',
        name: 'newsletter-ai',
        origin: 'newsletter-ai manifest',
        path: '~/Documents/projects/newsletter-ai/package.json',
        provider: 'openai',
        summary: 'Agent manifest suggests a local agent project.',
        tags: ['agent', 'openai', 'workflow'],
        updatedAt: 1_779_833_000_000,
        version: '0.4.0',
      },
      {
        category: 'mcp-server',
        confidence: 0.98,
        detector: 'mcp',
        displayName: 'figma',
        entrypoint: 'npx figma-mcp',
        group: 'newsletter-ai',
        id: '~/Documents/projects/newsletter-ai/.vscode/mcp.json::figma',
        kind: 'mcp',
        name: 'figma',
        origin: 'newsletter-ai MCP config',
        path: '~/Documents/projects/newsletter-ai/.vscode/mcp.json',
        provider: 'mcp',
        summary: 'MCP server endpoint: npx figma-mcp',
        tags: ['mcp', 'stdio'],
        updatedAt: 1_779_832_000_000,
        version: null,
      },
      {
        category: 'claude-plugin',
        confidence: 0.9,
        detector: 'claude',
        displayName: 'Memory Toolkit',
        entrypoint: '~/.claude/plugins/installed_plugins.json',
        group: 'Claude',
        id: '~/.claude/plugins/installed_plugins.json::memory-toolkit',
        kind: 'plugin',
        name: 'memory-toolkit',
        origin: 'Claude plugins',
        path: '~/.claude/plugins/installed_plugins.json',
        provider: 'claude',
        summary: 'Claude plugin registered locally.',
        tags: ['claude', 'plugin'],
        updatedAt: 1_779_831_000_000,
        version: '1.8.0',
      },
      {
        category: 'prompts',
        confidence: 0.96,
        detector: 'claude',
        displayName: 'incrementality-ai',
        entrypoint: '~/Documents/projects/incrementality-ai/CLAUDE.md',
        group: 'incrementality-ai',
        id: '~/Documents/projects/incrementality-ai/CLAUDE.md::incrementality-ai',
        kind: 'prompt',
        name: 'incrementality-ai',
        origin: 'incrementality-ai prompt',
        path: '~/Documents/projects/incrementality-ai/CLAUDE.md',
        provider: 'claude',
        summary: 'Project operating instructions discovered in the local workspace.',
        tags: ['md', 'claude'],
        updatedAt: 1_779_830_000_000,
        version: null,
      },
      {
        category: 'routines',
        confidence: 0.86,
        detector: 'local-agents',
        displayName: 'nightly-health-check',
        entrypoint: '~/Documents/projects/agentic-os/routines/nightly-health-check.sh',
        group: 'agentic-os',
        id: '~/Documents/projects/agentic-os/routines/nightly-health-check.sh::nightly-health-check',
        kind: 'routine',
        name: 'nightly-health-check',
        origin: 'agentic-os routines',
        path: '~/Documents/projects/agentic-os/routines/nightly-health-check.sh',
        provider: 'local',
        summary: 'Repeatable local workflow or script for operational checks.',
        tags: ['shell'],
        updatedAt: 1_779_836_000_000,
        version: null,
      },
      {
        category: 'n8n-workflow',
        confidence: 0.97,
        detector: 'n8n',
        displayName: 'Daily sync pipeline',
        entrypoint: '~/.n8n/workflows/daily-sync.n8n.json',
        group: 'n8n',
        id: '~/.n8n/workflows/daily-sync.n8n.json::daily-sync-pipeline',
        kind: 'workflow',
        name: 'daily-sync-pipeline',
        origin: 'n8n workflows',
        path: '~/.n8n/workflows/daily-sync.n8n.json',
        provider: 'n8n',
        summary: 'n8n workflow discovered from a local JSON workflow export.',
        tags: ['n8n', 'workflow', 'json'],
        updatedAt: 1_779_829_000_000,
        version: null,
      },
      {
        category: 'script',
        confidence: 0.7,
        detector: 'custom-rules',
        displayName: 'refresh-registry',
        entrypoint: '~/Documents/projects/agentic-os/scripts/refresh-registry.ts',
        group: 'agentic-os',
        id: '~/Documents/projects/agentic-os/scripts/refresh-registry.ts::refresh-registry',
        kind: 'automation',
        name: 'refresh-registry',
        origin: 'agentic-os scripts',
        path: '~/Documents/projects/agentic-os/scripts/refresh-registry.ts',
        provider: 'openai',
        summary: 'Script shows agentic or tool-calling behavior.',
        tags: ['ts'],
        updatedAt: 1_779_828_000_000,
        version: null,
      },
    ],
    totalItems: 46,
  },
  generatedAt: 1_779_845_400_000,
  runtime: {
    codexHome: '~/.codex',
    platform: 'Browser preview',
  },
  sources: [
    {
      id: 'workspace-allowlist',
      kind: 'scanner',
      label: 'Allowlisted workspaces',
      path: '6 roots',
      status: 'available',
    },
    {
      id: 'codex-home',
      kind: 'vendor',
      label: 'Codex home',
      path: '~/.codex',
      status: 'available',
    },
    {
      id: 'claude-home',
      kind: 'vendor',
      label: 'Claude home',
      path: '~/.claude',
      status: 'available',
    },
  ],
  usage: {
    activeThreads: 7,
    distinctWorkspaces: 3,
    logEntries24h: 1_284,
    topWorkspaces: [
      {
        cwd: '~/Documents/projects/agentic-os',
        lastUpdatedAt: 1_779_844_600_000,
        threadCount: 4,
        tokenTotal: 22_310,
      },
      {
        cwd: '~/Documents/projects/ops',
        lastUpdatedAt: 1_779_841_900_000,
        threadCount: 2,
        tokenTotal: 8_920,
      },
    ],
    totalTokens: 31_230,
    trackedThreads: 9,
    trend: [
      { day: 'Mon', tokenTotal: 2_300 },
      { day: 'Tue', tokenTotal: 4_800 },
      { day: 'Wed', tokenTotal: 2_050 },
      { day: 'Thu', tokenTotal: 6_540 },
      { day: 'Fri', tokenTotal: 5_980 },
      { day: 'Sat', tokenTotal: 3_240 },
      { day: 'Sun', tokenTotal: 6_320 },
    ],
  },
}
